import os
from tools.transcription import load_audio_file
from tools import context
from difflib import SequenceMatcher

import json

base_dir = os.path.dirname(__file__)

def test_deterministic_output_for_audio_file():
    """
    The idea of this test is that it compares an output generated by the transcriber to an expected output. Based on research,
    it doesn't look like whisper models can be trusted to provide an exact output for a given input, so allowing for a 90%
    accuracy window seems reasonable. It might be necessary to tweak this number. Larger files are likely to vary more, but 
    if we try to test a longer file, it's going to make the tests take a long time to run.

    It also felt most natural to me to move the audio file into this folder for the purposes of the test, we can decide whether to 
    remove it from the other place or just leave it in both. 
    """
    audio_path = os.path.join(base_dir, "audio", "test.mp3")

    result = load_audio_file(audio_path)

    result = result.lower()

    expected = "hello, my name is arya, i am a high quality speech voice, that you can use for your screen reading needs with iarrator which is the screen reader app built into windows. you can use my voice while interacting, and reading text with narrator, and i hope you give me a try."
    
    assert SequenceMatcher(None, result, expected).ratio() >= 0.9

# TODO - One roadblock at the moment is that the coordinator requires user input at various stages of the process. I could 
# make it so that it hardcodes a basic response to each prompt, but we debated adding the ability to kind of circumvent the coordinator
# for the GUI, and I think that would be nice for this test. 
# 
# This test won't pass yet. So it might not even be on the right track.
def test_output_generated(monkeypatch):
    """
    Runs the transcription process for a test file and ensures that an output file was generated for it
    and that it matches the expected structure. 
    """
    test_output_path = os.path.join(base_dir, "output")
    monkeypatch.setattr(context, "OUTPUT_DIR", test_output_path)

    os.makedirs(test_output_path, exist_ok=True)

    ctx = context._reset_context(audio_filename="test_audio.mp3")

    ctx.set_cleaned_transcript("hello, my name is arya, i am a high quality speech voice, that you can use for your screen reading needs with iarrator which is the screen reader app built into windows. you can use my voice while interacting, and reading text with narrator, and i hope you give me a try.")

    ctx.set_summary([
        "First bullet",
        "Second bullet",
        "Third bullet"
    ])

    files = [f for f in os.listdir(test_output_path) if f.endswith(".json")]

    assert len(files) == 1

    file_path = os.path.join(test_output_path, files[0])
    with open(file_path, "r", encoding="utf-8") as f:
        payload = json.load(f)

    assert "cleaned_transcript" in payload
    assert payload["cleaned_transcript"]

    assert len(payload["summary"]) == 3