import json
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from agent import _format_final_package, run_agent

from config import load_config
from agent import tool_box
from tools.transcription import load_audio_file
from difflib import SequenceMatcher

base_dir = Path(__file__).resolve().parents[1]

@pytest.fixture
def mock_openai():
    with patch("agent.client") as mock_client:
        mock_client.responses.create = AsyncMock()
        yield mock_client


@pytest.fixture(scope="session")
def agents():
    config = load_config(Path(base_dir / "agents.yaml"))
    return {agent["name"]: agent for agent in config["agents"]}


@pytest.fixture
def cleaner_agent(agents):
    return agents["cleaner"]


@pytest.fixture
def coordinator_agent(agents):
    return agents["coordinator"]


def test_deterministic_output_for_audio_file():
    """
    The idea of this test is that it compares an output generated by the transcriber to an expected output. Based on research,
    it doesn't look like whisper models can be trusted to provide an exact output for a given input, so allowing for a 90%
    accuracy window seems reasonable. It might be necessary to tweak this number. Larger files are likely to vary more, but 
    if we try to test a longer file, it's going to make the tests take a long time to run.

    It also felt most natural to me to move the audio file into this folder for the purposes of the test, we can decide whether to 
    remove it from the other place or just leave it in both. 
    """
    audio_path = base_dir / "tests" / "audio" / "test.mp3"

    result = load_audio_file(str(audio_path))

    result = result.lower()

    expected = "hello, my name is arya, i am a high quality speech voice, that you can use for your screen reading needs with iarrator which is the screen reader app built into windows. you can use my voice while interacting, and reading text with narrator, and i hope you give me a try."
    
    assert SequenceMatcher(None, result, expected).ratio() >= 0.9


def test_format_final_package_valid():
    payload = json.dumps({"transcription": "Hello.", "summary": ["Point one."]})
    result = _format_final_package(payload)
    assert result == "Hello.\n\nSummary\n- Point one."


def test_format_final_package_invalid_missing_summary():
    payload = json.dumps({"transcription": "Hello."})
    assert _format_final_package(payload) is None


def make_tool_call_response(name, arguments, call_id="call_1"):
    """Helper to build a fake LLM response that calls a tool."""
    item = MagicMock()
    item.type = "function_call"
    item.name = name
    item.arguments = json.dumps(arguments)
    item.call_id = call_id
    response = MagicMock()
    response.output = [item]
    return response


def make_text_response(text="Done."):
    item = MagicMock()
    item.type = "message"
    response = MagicMock()
    response.output = [item]
    response.output_text = text
    return response


async def test_cleaner_calls_tools_in_order(mock_openai, cleaner_agent):
    call_log = []

    # Simulate: get_transcript → set_cleaned_transcript → set_summary → done
    mock_openai.responses.create.side_effect = [
        make_tool_call_response("get_transcript", {}),
        make_tool_call_response("set_cleaned_transcript", {"text": "Clean text."}),
        make_tool_call_response("set_summary", {"bullets_json": '["Point one."]'}),
        make_text_response("- Point one."),
    ]

    # Patch tools to record calls
    with patch.object(tool_box, "run_tool", wraps=tool_box.run_tool, new_callable=AsyncMock) as mock_run:
        await run_agent(cleaner_agent, tool_box, "Summarize. n_bullets=3")
        tool_names = [call.args[0] for call in mock_run.call_args_list]

    assert tool_names[0] == "get_transcript"
    assert "set_cleaned_transcript" in tool_names
    assert "set_summary" in tool_names
    # Order matters: can't summarize before transcribing
    assert tool_names.index("get_transcript") < tool_names.index("set_summary")


async def test_coordinator_delegates_to_cleaner(mock_openai, coordinator_agent):
    mock_openai.responses.create.side_effect = [
        make_tool_call_response("talk_to_user", {"message": "Hi! Transcribing..."}),
        make_tool_call_response("cleaner", {"message": "Summarize with 5 bullets"}),
        make_text_response("- Point one."),
    ]

    with patch.object(tool_box, "run_tool", return_value="- Point one.", new_callable=AsyncMock) as mock_run:
        await run_agent(coordinator_agent, tool_box, None)
        called_tools = [c.args[0] for c in mock_run.call_args_list]

    assert "cleaner" in called_tools
    # Coordinator must NOT call get_transcript directly
    assert "get_transcript" not in called_tools

