import json
from difflib import SequenceMatcher
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from agent import _format_final_package, run_agent, tool_box
from config import load_config
from tools.transcription import load_audio_file

base_dir = Path(__file__).resolve().parents[1]

@pytest.fixture
def mock_openai():
    with patch("agent.client") as mock_client:
        mock_client.responses.create = AsyncMock()
        yield mock_client


@pytest.fixture(scope="session")
def agents():
    config = load_config(Path(base_dir / "agents.yaml"))
    return {agent["name"]: agent for agent in config["agents"]}


@pytest.fixture
def cleaner_agent(agents):
    return agents["cleaner"]


@pytest.fixture
def coordinator_agent(agents):
    return agents["coordinator"]

async def run_and_get_called_tools(
    agent,
    tool_box,
    *,
    wraps=tool_box,
    return_value=None,
):
    with patch.object(
        tool_box,
        "run_tool",
        new_callable=AsyncMock,
        wraps=wraps,
        return_value=return_value,
    ) as mock_run:
        await run_agent(agent, tool_box, None)

    return [call.args[0] for call in mock_run.call_args_list]


def test_deterministic_output_for_audio_file():
    """
    The idea of this test is that it compares an output generated by the transcriber to an expected
    output. Based on research, it doesn't look like whisper models can be trusted to provide an exact
    output for a given input, so allowing for a 90% accuracy window seems reasonable. It might be
    necessary to tweak this number. Larger files are likely to vary more, but if we try to test a
    longer file, it's going to make the tests take a long time to run.

    It also felt most natural to me to move the audio file into this folder for the purposes of the
    test, we can decide whether to remove it from the other place or just leave it in both.
    """
    audio_path = base_dir / "tests" / "audio" / "test.mp3"

    result = load_audio_file(str(audio_path))

    result = result.lower()

    expected = (
        "hello, my name is arya, i am a high quality speech voice, that you can use for your"
        " screen reading needs with narrator which is the screen reader app built into windows."
        " you can use my voice while interacting, and reading text with narrator, and i hope"
        " you give me a try."
    )

    assert SequenceMatcher(None, result, expected, autojunk=False).ratio() >= 0.9


def test_format_final_package_valid():
    payload = json.dumps({"transcription": "Hello.", "summary": ["Point one."]})
    result = _format_final_package(payload)
    assert result == "Hello.\n\nSummary\n- Point one."


def test_format_final_package_invalid_missing_summary():
    payload = json.dumps({"transcription": "Hello."})
    assert _format_final_package(payload) is None


def make_tool_call_response(name, arguments, call_id="call_1"):
    """Helper to build a fake LLM response that calls a tool."""
    item = MagicMock()
    item.type = "function_call"
    item.name = name
    item.arguments = json.dumps(arguments)
    item.call_id = call_id
    response = MagicMock()
    response.output = [item]
    return response


def make_text_response(text="Done."):
    item = MagicMock()
    item.type = "message"
    response = MagicMock()
    response.output = [item]
    response.output_text = text
    return response


async def test_cleaner_calls_tools_in_order(mock_openai, cleaner_agent):
    # Simulate: get_transcript → set_cleaned_transcript → set_summary → done
    mock_openai.responses.create.side_effect = [
        make_tool_call_response("get_transcript", {}),
        make_tool_call_response("set_cleaned_transcript", {"text": "Clean text."}),
        make_tool_call_response("set_summary", {"bullets_json": '["Point one."]', "n_bullets": "3"}),
        make_text_response("- Point one."),
    ]

    # Patch tools to record calls
    called_tools = await run_and_get_called_tools(cleaner_agent, tool_box)

    assert called_tools[0] == "get_transcript"
    assert "set_cleaned_transcript" in called_tools
    assert "set_summary" in called_tools
    # Order matters: can't summarize before transcribing
    assert called_tools.index("get_transcript") < called_tools.index("set_summary")


async def test_coordinator_delegates_to_cleaner(mock_openai, coordinator_agent):
    mock_openai.responses.create.side_effect = [
        make_tool_call_response("talk_to_user", {"message": "Hi! Transcribing..."}),
        make_tool_call_response("cleaner", {"message": "Summarize with 5 bullets"}),
        make_text_response("- Point one."),
    ]

    called_tools = await run_and_get_called_tools(coordinator_agent, tool_box)

    assert "cleaner" in called_tools
    # Coordinator must NOT call get_transcript directly
    assert "get_transcript" not in called_tools

